from selenium.webdriver.common.by import By


stream_screen = (By.CLASS_NAME, 'stream-display-ad__wrapper')
pause_play_button = (By.CSS_SELECTOR, 'button[data-a-target="player-play-pause-button"]')
pause_message = (By.CSS_SELECTOR, 'button[aria-label="Воспроизведение (пробел/k)"]')
start_watching = (By.CSS_SELECTOR, 'button[data-a-target="player-overlay-mature-accept"]')
mute_button = (By.CSS_SELECTOR, 'button[aria-label="Выкл. звук (m)"]')
settings_button = (By.CSS_SELECTOR, 'button[data-a-target="player-settings-button"]')
quality_video_button = (By.CSS_SELECTOR, 'button[data-a-target="player-settings-menu-item-quality"]')
field_of_settings = (By.CSS_SELECTOR, 'div[data-a-target="player-settings-menu"]')
list_of_video_qualities = (By.CSS_SELECTOR, 'div[class="Layout-sc-1xcs6mc-0 beAYWq"]')
quality_video_check = (By.CLASS_NAME, 'kLZqyf')
advanced_button = (By.CSS_SELECTOR, 'button[data-a-target="player-settings-menu-item-advanced"]')
advanced_settings_field = (By.CSS_SELECTOR, 'div[data-a-target="player-settings-menu"]')
video_statistics_window = (By.CSS_SELECTOR, 'div[data-a-target="player-overlay-video-stats"]')
indicator_of_mini_player = (By.CSS_SELECTOR, 'div[data-a-target="player-settings-submenu-advanced-toggle-mini"]')
view_button = (By.CLASS_NAME, 'navigation-link')
mini_player_window = (By.CLASS_NAME, 'video-player__overlay')
report_a_bug_button = (By.CSS_SELECTOR, 'button[data-a-target="player-settings-menu-item-report"]')
select_report = (
    By.CSS_SELECTOR, 'select[class="ScInputBase-sc-vu7u7d-0 ScSelect-sc-gz38t2-0'
                     ' gXVFsI AJDRH InjectLayout-sc-1i43xsx-0 bLZRbT tw-select"]', '«Заикание» звука и изображения')
first_report = (By.CSS_SELECTOR, 'option[value="stutter-both"]')
settings_menu_field = (By.CSS_SELECTOR, 'div[data-a-target="player-settings-menu"]')
list_of_hotkeys = (By.CLASS_NAME, 'tw-table-body')
theatre_mode_button = (By.CSS_SELECTOR, 'button[data-a-target="player-theatre-mode-button"]')
check_theatre_mode = (By.CSS_SELECTOR, 'div[data-a-player-state="theatre"]')
full_screen_button = (By.CSS_SELECTOR, 'button[data-a-target="player-fullscreen-button"]')
check_fullscreen_mode = (By.CSS_SELECTOR, 'button[aria-label="Обычный режим (f)"]')
open_chat_button = (By.CSS_SELECTOR, 'button[aria-label="Развернуть чат"]')
close_chat_button = (By.CSS_SELECTOR, 'button[aria-label="Свернуть чат"]')
chat_rules_ok_button = (By.CSS_SELECTOR, 'button[data-test-selector="chat-rules-ok-button"]')
message_to_chat_field = (By.CSS_SELECTOR, 'textarea[data-a-target="chat-input"]')
join_to_twitch_window = (By.CSS_SELECTOR, 'div[data-a-target="passport-modal"]')
community_button = (By.CSS_SELECTOR, 'button[data-test-selector="chat-viewer-list"]')
filter_field = (By.CSS_SELECTOR, 'div[class="tw-search-input"]')
spectators_button = (By.CSS_SELECTOR, 'button[class="InjectLayout-sc-1i43xsx-0 daSCXI"]')
spectators_field = (By.CSS_SELECTOR, 'div[class="Layout-sc-1xcs6mc-0 hvqWsm"]')
chat_settings_button = (By.CSS_SELECTOR, 'button[data-a-target="chat-settings"]')
chat_filter_button = (By.CSS_SELECTOR, 'button[data-test-selector="chat-filter-item-click-target"]')
enable_filtration_in_chat = (By.CSS_SELECTOR, 'div[data-test-selector="chat-filter-top-toggle"]')
community_points_button = (By.CSS_SELECTOR, 'div[data-test-selector="community-points-summary"]')
channel_points_reward = (By.ID, 'channel-points-reward-center-body')
chat_send_button = (By.CSS_SELECTOR, 'button[data-a-target="chat-send-button"]')
follow_button = (By.CSS_SELECTOR, 'button[data-a-target="follow-button"]')
subscription_info = (By.CSS_SELECTOR, 'div[class="Layout-sc-1xcs6mc-0 jnwfls support-panel-container"]')
subscribe_button = (By.CSS_SELECTOR, 'button[data-test-selector="subscribe-button__dropdown"]')
sing_in_window = (By.CSS_SELECTOR, 'div[data-a-target="passport-modal"]')
subscribe_main_button = (By.CSS_SELECTOR, 'button[aria-label="Подписаться $4.99"]')
